# Generated by Django 5.1.1 on 2024-10-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(""" INSERT INTO store_collection (title)
                          VALUES(coll1)""","""DELETE FROM store_collection
                          WHERE title='coll1' """)
    ]
